import{Community,isMaster,isHost,scoreCards,friendlyError}from'./community.js';import{AudioEngine}from'./audio.js';
const $=id=>document.getElementById(id),community=new Community(),audio=new AudioEngine();let authMode='signin',busy=false,current='home',sort='best',cards=[],directory={},runs={},stackerRuns={},stackerHidden={},moderation={},challenges={},generation=0;let stopMessages=null,installPrompt=null;
const format=n=>Number(n||0).toLocaleString(),node=(tag,cls='',text='')=>{const e=document.createElement(tag);e.className=cls;e.textContent=text;return e;},button=(text,fn,cls='secondary')=>{const b=node('button',cls,text);b.type='button';b.addEventListener('click',fn);return b;};
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,4500);}
function status(id,text){$(id).textContent=text;$(id).hidden=!text;}
function showAccount(){$('account-dialog').showModal();}
function showEmpty(el,text){el.replaceChildren(node('p','empty-state',text));}
function initials(name){return Array.from(name||'?').slice(0,2).join('').toUpperCase();}
function route(){const target=location.hash.slice(1)||'home';current=['home','hall','players','messages','host','master'].includes(target)?target:'home';if(['messages','host','master'].includes(current)&&!community.profile){showAccount();current='home';}if(current==='master'&&!isMaster(community.profile))current='home';for(const v of document.querySelectorAll('.view'))v.hidden=v.id!==current+'-view';for(const a of document.querySelectorAll('[data-nav]'))a.classList.toggle('active',a.dataset.nav===current);document.title=current==='home'?'SUJA Game Center':`${({hall:'Hall of Fame',players:'Player Cards',messages:'Message Center',host:'Host Center',master:'Master Controls'})[current]} · SUJA`;if(current==='messages')loadMessages();if(current==='host')renderChallenges();if(current==='master')loadMaster();window.scrollTo(0,0);}
window.addEventListener('hashchange',route);for(const b of document.querySelectorAll('[data-route]'))b.addEventListener('click',()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close());location.hash=b.dataset.route;if(current===b.dataset.route)route();});
function updateProfile(p){generation++;stopMessages?.();stopMessages=null;directory={};runs={};stackerRuns={};stackerHidden={};moderation={};cards=[];challenges={};$('account-name').textContent=p?.displayName||'User Login';$('avatar').textContent=p?initials(p.displayName):'☺';$('welcome').textContent=p?`Hey, ${p.displayName}.`:'Clock in. Game on.';$('welcome-note').textContent=p?'Your next personal best starts here. Pick a game and make your next shift count.':'Sign in once. Your player, scores, and crew come with you.';$('dashboard').textContent=p?'My player card →':'Open my dashboard →';$('auth-view').hidden=!!p;$('profile-view').hidden=!p;$('profile-name').textContent=p?.displayName||'';$('profile-role').textContent=p?.role?.toUpperCase()||'PLAYER';$('master-link').hidden=!isMaster(p);$('message-id').textContent=p?.messageId||'Sign in to get your ID';$('host-request').hidden=isHost(p);$('host-tools').hidden=!isHost(p);renderData();if(p)refresh();if(current==='master'&&!isMaster(p))location.hash='home';}
community.subscribe(updateProfile);
async function refresh(){if(!community.profile){status('community-status','Sign in to see your crew’s records. Guest play is always available.');return;}const gen=generation;try{const data=await Promise.all([community.read('directory'),community.read('runs'),community.read('moderation'),community.read('challenges')]);if(gen!==generation)return;[directory,runs,moderation,challenges]=data.map(x=>x||{});[stackerRuns,stackerHidden]=await Promise.all([community.read('stackerRuns').catch(()=>({})),community.read('stackerModeration').catch(()=>({}))]);if(gen!==generation)return;cards=scoreCards(directory,runs,moderation,stackerRuns,stackerHidden);status('community-status','');renderData();if(current==='master')loadMaster();}catch(e){if(gen===generation)status('community-status',friendlyError(e));}}
function standingRows(el,list,key,limit){el.replaceChildren();const timeKey=key==='race'?'raceTime':key==='challengeScore'?'challengeTime':null;const has=list.filter(p=>p[key]>0).sort((a,b)=>b[key]-a[key]||(timeKey?(a[timeKey]||0)-(b[timeKey]||0):0)||a.displayName.localeCompare(b.displayName));if(!has.length){showEmpty(el,community.profile?'No scores yet. Play the first shift!':'Sign in to see the crew’s high scores.');return;}let rank=0,prior=-1,priorTime=-1;has.slice(0,limit||has.length).forEach((p,i)=>{if(p[key]!==prior||timeKey&&p[timeKey]!==priorTime)rank=i+1;prior=p[key];priorTime=p[timeKey];const row=button('',()=>openCard(p.id),'standing-row');row.append(node('span','rank',String(rank).padStart(2,'0')),node('span','player-avatar',initials(p.displayName)),node('span','player-nick',p.displayName+(key==='race'?` · ${Math.floor(p.raceTime/60)}:${String(p.raceTime%60).padStart(2,'0')}`:'')),node('strong','standing-score',format(p[key])));el.append(row);});}
function renderData(){const mine=cards.find(c=>c.id===community.profile?.profileId);$('my-best').textContent=mine?format(mine.best):'—';$('my-games').textContent=mine?format(mine.games):'—';standingRows($('home-standings'),cards,'best',3);standingRows($('leaderboard'),cards,sort);renderPlayers();renderChallenges();}
const titles={stacker:'Pallet Stacker · best arcade score',race:'Four-juice race · total points',best:'Best 3-minute shift',endless:'Best endless run',total:'Lifetime points',bottles:'Most bottles stood',combo:'Longest combo',games:'Most shifts played'};for(const b of document.querySelectorAll('[data-sort]'))b.addEventListener('click',()=>{sort=b.dataset.sort;$('board-title').textContent=titles[sort];$('board-game').textContent=sort==='stacker'?'Pallet Stacker':'Bottles Up!';for(const c of document.querySelectorAll('[data-sort]'))c.classList.toggle('selected',c===b);standingRows($('leaderboard'),cards,sort);});
function renderPlayers(){const el=$('player-grid');el.replaceChildren();const q=$('player-search').value.toLowerCase();const found=cards.filter(c=>c.displayName.toLowerCase().includes(q));if(!found.length){showEmpty(el,community.profile?'No matching players yet.':'Sign in to meet the SUJA crew.');return;}for(const p of found){const b=button('',()=>openCard(p.id),'player-card');b.append(node('span','card-avatar',initials(p.displayName)),node('h2','',p.displayName),node('span','role-pill',p.role==='master'?'Master host':p.role==='host'?'Host':'Player'));const stats=node('div','card-stats');stats.append(node('strong','',format(p.best)),node('span','','BEST SHIFT'));b.append(stats,node('p','subtle',`${format(p.games)} shifts · ${format(p.bottles)} bottles`));el.append(b);}}
$('player-search').addEventListener('input',renderPlayers);
function openCard(id){const p=cards.find(c=>c.id===id)||{displayName:community.profile?.displayName||'Player',role:community.profile?.role||'player',best:0,games:0,bottles:0,combo:0,total:0,quality:0};const el=$('player-detail');el.replaceChildren(node('span','card-avatar',initials(p.displayName)),node('p','eyebrow',p.role==='master'?'MASTER HOST':'SUJA CREW'),node('h2','',p.displayName));const grid=node('div','detail-stats');for(const[label,key]of[['Pallet Stacker','stacker'],['Stacker cases','stackerCases'],['Best shift','best'],['Four-juice race','race'],['Lifetime points','total'],['Bottles stood','bottles'],['Shifts played','games'],['Best combo','combo'],['Defects caught','quality']]){const n=node('div');n.append(node('strong','',format(p[key])),node('span','',label));grid.append(n);}el.append(grid);const a=node('a','primary','Play Bottles Up! →');a.href='./bottles-up.html';el.append(a);const stack=node('a','secondary','Play Pallet Stacker →');stack.href='./play.html?game=pallet-stacker';el.append(stack);document.querySelectorAll('dialog[open]').forEach(d=>d.close());$('player-dialog').showModal();}
$('account').addEventListener('click',showAccount);$('dashboard').addEventListener('click',()=>community.profile?openCard(community.profile.profileId):showAccount());$('my-card').addEventListener('click',()=>openCard(community.profile.profileId));for(const mode of['signin','signup'])$(mode+'-tab').addEventListener('click',()=>{authMode=mode;$('signin-tab').classList.toggle('selected',mode==='signin');$('signup-tab').classList.toggle('selected',mode==='signup');$('auth-submit').textContent=mode==='signin'?'Sign in →':'Create my player →';status('auth-status','');});
$('auth-form').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;$('auth-submit').disabled=true;status('auth-status','Connecting…');try{const p=await community[authMode==='signin'?'signIn':'signUp']($('email').value,$('nickname').value);$('account-dialog').close();$('auth-form').reset();status('auth-status','');toast(`Welcome, ${p.displayName}.`);route();}catch(e){status('auth-status',friendlyError(e));}finally{busy=false;$('auth-submit').disabled=false;}});
$('signout').addEventListener('click',async()=>{try{await community.signOut();$('account-dialog').close();location.hash='home';toast('You’re signed out.');}catch(e){toast(friendlyError(e));}});
$('request-host').addEventListener('click',async()=>{try{await community.requestHost();status('request-status','Your request is with Sean.');$('request-host').disabled=true;}catch(e){status('request-status',friendlyError(e));}});
$('challenge-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const code=await community.createChallenge($('challenge-title').value,$('challenge-mode').value);status('challenge-create-status',`Challenge ${code} created. Open it when your crew is ready.`);$('challenge-title').value='';await refresh();}catch(e){status('challenge-create-status',friendlyError(e));}finally{b.disabled=false;}});
function renderChallenges(){const el=$('challenge-list');el.replaceChildren();if(!isHost(community.profile))return;const items=Object.entries(challenges).filter(([id,c])=>c.hostId===community.profile.profileId||isMaster(community.profile)).sort((a,b)=>b[1].createdAt-a[1].createdAt);if(!items.length){showEmpty(el,'Your challenges will appear here.');return;}for(const[code,c]of items){const box=node('details','surface challenge');const title=node('summary','',c.title+' · '+c.status);box.append(title);const info=node('p','',`Code ${code} · ${c.mode==='race'?'Four-juice race · Total points wins':'3-minute shift'} · Hosted by ${c.hostName}`);box.append(info);const controls=node('div','challenge-actions');controls.append(button('Copy invite',()=>copy(`${location.origin}/sujagamecenter/bottles-up.html?challenge=${code}`,'Invite link copied.')));if(c.status==='lobby')controls.append(button('Open challenge',async()=>{try{await community.setChallenge(code,'open');await refresh();}catch(e){toast(friendlyError(e));}},'primary'));if(c.status==='open'){const a=node('a','primary','Play challenge →');a.href=`./bottles-up.html?challenge=${code}`;controls.append(a);controls.append(button('Close & lock results',async()=>{try{await community.setChallenge(code,'closed');await refresh();}catch(e){toast(friendlyError(e));}}));}box.append(controls);const best=cards.map(p=>{const top=p.runs.filter(r=>r.challengeId===code&&r.seed===c.seed&&r.mode===(c.mode||'shift')).sort((a,b)=>b.score-a.score||a.duration-b.duration)[0];return {...p,challengeScore:top?.score||0,challengeTime:top?.duration||0};});const list=node('div');standingRows(list,best,'challengeScore');box.append(list);el.append(box);}}
$('join-form').addEventListener('submit',async e=>{e.preventDefault();if(!community.profile){showAccount();return;}const code=$('join-code').value.trim().toUpperCase();try{const c=await community.read(`challenges/${code}`);if(!c)throw new Error('That challenge was not found.');if(c.status==='closed')throw new Error('This challenge has closed. Ask your host for a new code.');if(c.status==='lobby'){status('join-status',`${c.title} is waiting for the host to open it. Try again shortly.`);return;}location.assign(`./bottles-up.html?challenge=${code}`);}catch(e){status('join-status',friendlyError(e));}});
async function loadMaster(){if(!isMaster(community.profile))return;const gen=generation;try{const req=await community.read('hostRequests')||{};if(gen!==generation)return;$('host-requests').replaceChildren();const entries=Object.entries(req);if(!entries.length)showEmpty($('host-requests'),'No pending host requests.');for(const[id,r]of entries){const row=node('div','management-row');row.append(node('strong','',r.displayName),button('Approve host',async()=>{try{await community.setHost(id,true);await refresh();}catch(e){toast(friendlyError(e));}},'primary'));$('host-requests').append(row);}$('master-players').replaceChildren();for(const p of cards){const row=node('div','management-row');row.append(node('strong','',p.displayName),node('span','role-pill',p.role));if(p.role!=='master')row.append(button(p.role==='host'?'Remove host access':'Make host',async()=>{try{await community.setHost(p.id,p.role!=='host');await refresh();}catch(e){toast(friendlyError(e));}}));else row.append(node('span','subtle','Protected'));$('master-players').append(row);}
 const recent=cards.flatMap(p=>p.runs.map(r=>({...r,uid:p.id}))).sort((a,b)=>b.finishedAt-a.finishedAt).slice(0,25);$('score-review').replaceChildren();if(!recent.length)showEmpty($('score-review'),'No runs to review yet.');for(const r of recent){const row=node('div','management-row');row.append(node('span','',`${r.displayName} · ${format(r.score)} · ${r.mode}`),button('Exclude score',async()=>{try{await community.hideRun(r.uid,r.id);await refresh();toast('Score excluded from standings.');}catch(e){toast(friendlyError(e));}}));$('score-review').append(row);}
 const stackRecent=Object.entries(stackerRuns||{}).flatMap(([uid,records])=>Object.entries(records||{}).filter(([id])=>!stackerHidden?.[uid]?.[id]).map(([id,r])=>({...r,id,uid}))).sort((a,b)=>b.finishedAt-a.finishedAt).slice(0,25);
 for(const r of stackRecent){const row=node('div','management-row');row.append(node('span','',`${r.displayName} · ${format(r.score)} · Pallet Stacker`),button('Exclude score',async()=>{try{await community.write(`stackerModeration/${r.uid}/${r.id}`,true);await refresh();toast('Score excluded.');}catch(e){toast(friendlyError(e));}}));$('score-review').append(row);}
 }catch(e){status('community-status',friendlyError(e));}}
async function loadMessages(){if(!community.profile)return;stopMessages?.();showEmpty($('mailbox'),'Loading your messages…');const uid=community.profile.profileId;stopMessages=community.watch(`mailboxes/${uid}`,data=>{if(community.profile?.profileId!==uid)return;const el=$('mailbox');el.replaceChildren();const messages=Object.entries(data||{}).sort((a,b)=>b[1].createdAt-a[1].createdAt);if(!messages.length){showEmpty(el,'No messages yet. Share your Message ID with a coworker.');return;}for(const[id,m]of messages){const sent=m.fromUid===uid;const article=node('article','message');article.append(node('strong','',sent?`To ${m.toName}`:`From ${m.fromName}`),node('span','subtle',new Date(m.createdAt).toLocaleString()),node('p','message-text',m.body));const actions=node('div','message-actions');if(!sent)actions.append(button('Reply',()=>{$('to-id').value=m.fromMessageId||'';$('to-name').value=m.fromName;$('message-body').focus();},'text-button'));actions.append(button('Delete',async()=>{try{await community.deleteMessage(id);}catch(e){toast(friendlyError(e));}},'text-button'));article.append(actions);el.append(article);}},e=>showEmpty($('mailbox'),friendlyError(e)));}
$('refresh-messages').addEventListener('click',loadMessages);$('message-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await community.sendMessage($('to-id').value,$('to-name').value,$('message-body').value);$('message-body').value='';status('message-status','Message sent.');}catch(e){status('message-status',friendlyError(e));}finally{b.disabled=false;}});
async function copy(text,message){try{await navigator.clipboard.writeText(text);toast(message);}catch{toast('Select and copy the text to share it.');}}$('copy-id').addEventListener('click',()=>community.profile&&copy(community.profile.messageId,'Message ID copied. Share your nickname too.'));$('share').addEventListener('click',async()=>{const data={title:'SUJA Game Center',text:'A little friendly competition for the crew. Bottles Up!',url:'https://seansommer.github.io/sujagamecenter/'};if(navigator.share){try{await navigator.share(data);return;}catch(e){if(e.name==='AbortError')return;}}copy(data.url,'Game Center link copied.');});
for(const b of document.querySelectorAll('.refresh'))b.addEventListener('click',refresh);for(const b of document.querySelectorAll('[data-close]'))b.addEventListener('click',()=>$(b.dataset.close).close());const dark=localStorage.getItem('sujaTheme')==='dark';document.documentElement.dataset.theme=dark?'dark':'light';$('theme').addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('sujaTheme',next);});$('music').addEventListener('click',async()=>{await audio.unlock();audio.active=!audio.active;$('music').textContent=audio.active?'Music on ♫':'Music off ♫';});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});$('install').addEventListener('click',async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;}else $('install-dialog').showModal();});window.addEventListener('online',()=>refresh());
community.init().catch(e=>status('community-status',friendlyError(e)));route();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});

$('share-bottles').addEventListener('click',async()=>{const data={title:'Bottles Up!',text:'Stand them up. Rack up the points. Created by Paul Cruz.',url:'https://seansommer.github.io/sujagamecenter/bottles-up.html'};if(navigator.share){try{await navigator.share(data);return;}catch(e){if(e.name==='AbortError')return;}}copy(data.url,'Bottles Up! link copied.');});
