import { FIREBASE_CONFIG,SDK_VERSION,COMMUNITY_PATH,FIREBASE_APP_NAME,isConfigured } from './config.js';
import {loginKey,normalizeEmail,normalizeNickname,validatePlayer,createMessageId,messageKey} from './identity.js';
export const isMaster=p=>p?.role==='master';
export const isHost=p=>['master','host'].includes(p?.role);
export class Community{
 constructor(){this.profile=null;this.listeners=new Set();this.generation=0;}
 emit(p){this.profile=p;this.listeners.forEach(f=>f(p));}
 subscribe(f){this.listeners.add(f);f(this.profile);return()=>this.listeners.delete(f);}
 ref(path=''){return this.api.ref(this.db,COMMUNITY_PATH+(path?'/'+path:''));}
 async init(){if(this.ready)return this;if(this.initializing)return this.initializing;this.initializing=this.connect();try{return await this.initializing;}finally{this.initializing=null;}}
 async connect(){if(!isConfigured())throw new Error('The SUJA community is being set up. Guest play is ready.');const modules=await Promise.all(['app','auth','database'].map(s=>import(`https://www.gstatic.com/firebasejs/${SDK_VERSION}/firebase-${s}.js`)));this.api=Object.assign({},...modules);const app=this.api.getApps().find(a=>a.name===FIREBASE_APP_NAME)||this.api.initializeApp(FIREBASE_CONFIG,FIREBASE_APP_NAME);this.auth=this.api.getAuth(app);this.db=this.api.getDatabase(app);await this.api.setPersistence(this.auth,this.api.browserLocalPersistence);await this.auth.authStateReady();await new Promise((resolve,reject)=>{let first=true;this.stopAuth=this.api.onAuthStateChanged(this.auth,u=>{const restored=this.restore(u);if(first){first=false;restored.then(resolve,reject);}},reject);});this.ready=true;return this;}
 async restore(user){const g=++this.generation;this.stopSession?.();this.stopProfile?.();this.emit(null);if(!user)return;await new Promise(resolve=>{this.stopSession=this.api.onValue(this.ref(`sessions/${user.uid}`),snap=>{if(g!==this.generation){resolve();return;}this.stopProfile?.();const id=snap.val()?.profileId;if(!id){this.emit(null);resolve();return;}this.stopProfile=this.api.onValue(this.ref(`users/${id}`),p=>{if(g===this.generation)this.emit(p.exists()?{...p.val(),profileId:id}:null);resolve();},()=>{if(g===this.generation)this.emit(null);resolve();});},()=>{if(g===this.generation)this.emit(null);resolve();});});}
 async ensure(){await this.init();return this.auth.currentUser||(await this.api.signInAnonymously(this.auth)).user;}
 async read(path){const s=await this.api.get(this.ref(path));return s.val();}
 async write(path,data){return this.api.set(this.ref(path),data);}
 require(role='player'){if(!this.profile)throw new Error('Sign in at SUJA Game Center first.');if(role==='master'&&!isMaster(this.profile))throw new Error('Master access required.');if(role==='host'&&!isHost(this.profile))throw new Error('Host access required.');return this.profile;}
 async signIn(email,displayName){validatePlayer(email,displayName);const user=await this.ensure(),key=await loginKey(email,displayName);let id=await this.read(`loginLookup/${key}`);
  if(!id)throw new Error('That SUJA player was not found. Create a new player, or check your email and nickname.');await this.write(`sessions/${user.uid}`,{profileId:id,loginKey:key});const p=await this.read(`users/${id}`);if(!p)throw new Error('This player is unavailable.');this.emit({...p,profileId:id});return this.profile;
 }
 async signUp(email,displayName){validatePlayer(email,displayName);const user=await this.ensure(),key=await loginKey(email,displayName);if(await this.read(`loginLookup/${key}`))throw new Error('That player already exists. Choose Sign in.');const id=this.api.push(this.ref('users')).key;await this.createProfile({user,id,key,email,displayName,role:'player'});await this.write(`sessions/${user.uid}`,{profileId:id,loginKey:key});this.emit({...await this.read(`users/${id}`),profileId:id});return this.profile;}
 async createProfile({user,id,key,email,displayName,role}){const messageId=createMessageId(),lookup=await messageKey(messageId,displayName),now=Date.now();const p={email:normalizeEmail(email),displayName:displayName.trim(),role,ownerAuthUid:user.uid,loginKey:key,messageId,messageLookupKey:lookup,createdAt:now};
  // Claim all identity records in one atomic write. Rules reject concurrent collisions.
  await this.api.update(this.ref(),{[`users/${id}`]:p,[`directory/${id}`]:{displayName:p.displayName,role,createdAt:now},[`loginLookup/${key}`]:id,[`messageIds/${messageId}`]:id,[`messageLookup/${lookup}`]:id});
 }
 async signOut(){if(this.auth?.currentUser)await this.api.remove(this.ref(`sessions/${this.auth.currentUser.uid}`)).catch(()=>{});await this.api.signOut(this.auth);this.emit(null);}
 watch(path,callback,onError=()=>{}){return this.api.onValue(this.ref(path),s=>callback(s.val()),onError);}
 async requestHost(){const p=this.require();await this.write(`hostRequests/${p.profileId}`,{displayName:p.displayName,requestedAt:this.api.serverTimestamp()});}
 async setHost(id,enabled){const p=this.require('master');if(id===p.profileId)throw new Error('Your master account is protected.');const user=await this.read(`users/${id}`);if(!user||user.role==='master')throw new Error('This account is protected.');await this.api.update(this.ref(),{[`users/${id}/role`]:enabled?'host':'player',[`directory/${id}/role`]:enabled?'host':'player',[`hostRequests/${id}`]:null});}
 async saveRun(id,result,challengeId=''){const p=this.require();if(result.mode==='practice')throw new Error('Practice scores stay on this device.');if(!/^[a-zA-Z0-9-]{8,80}$/.test(id))throw new Error('Invalid run.');const path=`runs/${p.profileId}/${id}`;const existing=await this.read(path);if(existing)return existing;const run={...result,displayName:p.displayName,challengeId,finishedAt:this.api.serverTimestamp()};await this.write(path,run);return run;}
 async createChallenge(title){const p=this.require('host');title=String(title).trim().slice(0,60);if(!title)throw new Error('Give your challenge a name.');for(let i=0;i<5;i++){const code=createMessageId().slice(0,6);try{await this.write(`challenges/${code}`,{title,hostId:p.profileId,hostName:p.displayName,seed:crypto.getRandomValues(new Uint32Array(1))[0],status:'lobby',createdAt:this.api.serverTimestamp()});return code;}catch(e){if(await this.read(`challenges/${code}`))continue;throw e;}}throw new Error('Please try creating the challenge again.');}
 async setChallenge(code,status){this.require('host');if(!['open','closed'].includes(status))throw new Error('Invalid challenge status.');await this.api.update(this.ref(`challenges/${code}`),{status});}
 async sendMessage(messageId,nickname,body){const p=this.require();body=String(body).trim();if(!body||body.length>2000)throw new Error('Write a message up to 2,000 characters.');const key=await messageKey(messageId.trim().toUpperCase(),nickname);const to=await this.read(`messageLookup/${key}`);if(!to)throw new Error('No player matches that Message ID and nickname.');if(to===p.profileId)throw new Error('Choose another player.');const recipient=await this.read(`directory/${to}`);const id=this.api.push(this.ref('mailboxes')).key;const m={fromUid:p.profileId,fromName:p.displayName,fromMessageId:p.messageId,toUid:to,toName:recipient.displayName,recipientKey:key,body,createdAt:this.api.serverTimestamp()};await this.api.update(this.ref(),{[`mailboxes/${to}/${id}`]:m,[`mailboxes/${p.profileId}/${id}`]:m});}
 async deleteMessage(id){const p=this.require();await this.api.remove(this.ref(`mailboxes/${p.profileId}/${id}`));}
 async hideRun(uid,id){this.require('master');await this.write(`moderation/${uid}/${id}`,true);}
}
export function scoreCards(directory={},runs={},hidden={}){return Object.entries(directory).map(([id,p])=>{const entries=Object.entries(runs[id]||{}).filter(([rid,r])=>!hidden[id]?.[rid]&&r.version==='1.0.0'&&['shift','endless'].includes(r.mode)).map(([rid,r])=>({...r,id:rid}));const shifts=entries.filter(r=>r.mode==='shift'),endless=entries.filter(r=>r.mode==='endless');return{id,...p,runs:entries,best:Math.max(0,...shifts.map(r=>r.score)),endless:Math.max(0,...endless.map(r=>r.score)),total:entries.reduce((a,r)=>a+r.score,0),bottles:entries.reduce((a,r)=>a+r.stood,0),combo:Math.max(0,...entries.map(r=>r.maxCombo)),games:entries.length,quality:entries.reduce((a,r)=>a+r.rejected,0)};}).sort((a,b)=>b.best-a.best||a.displayName.localeCompare(b.displayName));}
export function friendlyError(e){const m=String(e?.message||e);return /permission.?denied/i.test(m)?'The SUJA community connection is not ready yet. Please contact Sean, or play as a guest.':/network|fetch|offline/i.test(m)?'Couldn’t connect. Check your internet connection and try again.':m;}
